name: Server

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
      - name: Creating env file
        run: |
          touch server/.env
          echo PORT=${{ secrets.PORT }} >> server/.env
          echo METEO_CONTROLLER_IP=${{ secrets.METEO_CONTROLLER_IP }} >> server/.env
          echo METEO_CONTROLLER_PORT=${{ secrets.METEO_CONTROLLER_PORT }} >> server/.env
          echo DB_HOST=br_postgres >> server/.env
          echo DB_PORT=9801 >> server/.env
          echo DB_USER=${{ secrets.DB_USER }} >> server/.env
          echo DB_PWD= >> server/.env
          echo DB_NAME=${{ secrets.DB_NAME }} >> server/.env
          cat server/.env
      - name: Building
        run: |
          docker-compose -f ./docker-compose.yml up -d --build br_srv
